name: taller_trapillo_store
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2
  flutter: ^3.29.3


dependencies:
  http: ^1.2.1
  dio: ^5.4.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0  
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  generate: true
  assets:
    - assets/images/
  uses-material-design: true
